import type { Metadata } from "next";
// eslint-disable-next-line import/order
import { Inter } from "next/font/google";

import { ReactNode } from "react";

import "./globals.css";
import "../styles/grid.scss";
import "../styles/flex.scss";
import "../styles/fonts.scss";
import "../styles/common.scss";
import { Header } from "@Basket/components/organisms/header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
